### SQL

default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000


development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ketchup
  pool: 5
  username: root
  password: jakekot8

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ketchup
  pool: 5
  username: root
  password: jakekot8

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ketchup
  pool: 5
  username: root
  password: jakekot8


